### PR TITLE
Bump browserslist-rs 0.16.0

### PR DESCRIPTION
**Pull request by chenjiahan**
Bump browserslist-rs 0.16.0, be consistent with Parcel and SWC:

- https://github.com/parcel-bundler/parcel/pull/9838
- https://github.com/swc-project/swc/pull/9023

Changes

- https://github.com/browserslist/browserslist-rs/releases/tag/v0.16.0

### CODE REVIEW

**Comment by chenjiahan** [comment]
@mischnic I have fixed the CI, can you approve the workflow again? ❤️

**Comment by mischnic** [comment]
There's apparently still a failing test:
```
---- bundler::tests::test_bundle stdout ----
thread 'bundler::tests::test_bundle' panicked at src/bundler.rs:1121:5:
assertion `left == right` failed
  left: "@supports (foo: bar) or (color: red) {\n  .b {\n    color: green;\n  }\n}\n\n.a {\n  color: red;\n}\n"
 right: "@supports (color: red) or (foo: bar) {\n  .b {\n    color: green;\n  }\n}\n\n.a {\n  color: red;\n}\n"
stack backtrace:
   0:     0x5577d2c86156 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5577d2c86156 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at 
```

**Comment by chenjiahan** [comment]
I can not reproduce this failure in my device:

image

image

I'm not sure if this can be fixed by retry the CI, it would be great if you could help to confirm that.

**Comment by mischnic** [comment]
@devongovett Sounds like some nondeterministic map/list? I guess this really shouldn't happen?

**Comment by devongovett** [comment]
It's this, just haven't gotten around to fixing it https://github.com/parcel-bundler/lightningcss/issues/137

**Review by devongovett — APPROVED** [review]

**Pull request merged**
